### ISSUE TITLE
Policy does not work for Karpenter using custom launch template

### ISSUE THREAD

**Issue by garyyang6** [terraform-aws-modules/terraform-aws-iam#284] opened 2022-10-05 18:55 UTC
## Description

The code as follows creates a policy named arn:aws:iam::AccountID:policy/AmazonEKS_Karpenter_Controller_Policy-09876543211234567800000001 and attach it to the role KarpenterNodeRole-karpenter-eks-uswest.
```
resource "aws_iam_instance_profile" "karpenter" {
  name = "KarpenterNodeInstanceProfile-${var.cluster_name}"
  role = module.eks.eks_managed_node_groups["${var.cluster_name}"].iam_role_name
}

module "karpenter_irsa" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  version = "5.4.0"

  role_name                               = "KarpenterNodeRole-${var.cluster_name}"

  attach_karpenter_controller_policy      = true

  karpenter_tag_key                       = "karpenter.sh/discovery/${var.cluster_name}"
  karpenter_controller_cluster_id         = module.eks.cluster_id

  karpenter_controller_ssm_parameter_arns = [
    "arn:${local.partition}:ssm:*:*:parameter/aws/service/*"
  ]

  karpenter_controller_node_iam_role_arns = [
    module.eks.eks_managed_node_groups["${var.cluster_name}"].iam_role_arn
  ]

  oidc_providers = {
    ex = {
      provider_arn               = module.eks.oidc_provider_arn
      namespace_service_accounts = ["karpenter:karpenter"]
    }
  }
}
```
Below is the policy created by above code:
```
{
    "Statement": [
        {
            "Action": [
                "pricing:GetProducts",
                "ec2:DescribeSubnets",
                "ec2:DescribeSpotPriceHistory",
                "ec2:DescribeSecurityGroups",
                "ec2:DescribeLaunchTemplates",
                "ec2:DescribeInstances",
                "ec2:DescribeInstanceTypes",
                "ec2:DescribeInstanceTypeOfferings",
                "ec2:DescribeImages",
                "ec2:DescribeAvailabilityZones",
                "ec2:CreateTags",
                "ec2:CreateLaunchTemplate",
                "ec2:CreateFleet"
            ],
            "Effect": "Allow",
            "Resource": "*",
            "Sid": ""
        },
        {
            "Action": [
                "ec2:TerminateInstances",
                "ec2:DeleteLaunchTemplate"
            ],
            "Condition": {
                "StringEquals": {
                    "ec2:ResourceTag/karpenter.sh/discovery/karpenter-eks-uswest": "karpenter-eks-uswest"
                }
            },
            "Effect": "Allow",
            "Resource": "*",
            "Sid": ""
        },
        {
            "Action": "ec2:RunInstances",
            "Condition": {
                "StringEquals": {
                    "ec2:ResourceTag/karpenter.sh/discovery/karpenter-eks-uswest": "karpenter-eks-uswest"
                }
            },
            "Effect": "Allow",
            "Resource": [
                "arn:aws:ec2:*:AccountID:security-group/*",
                "arn:aws:ec2:*:AccountID:launch-template/*"
            ],
            "Sid": ""
        },
        {
            "Action": "ec2:RunInstances",
            "Effect": "Allow",
            "Resource": [
                "arn:aws:ec2:*::image/*",
                "arn:aws:ec2:*:AccountID:volume/*",
                "arn:aws:ec2:*:AccountID:subnet/*",
                "arn:aws:ec2:*:AccountID:spot-instances-request/*",
                "arn:aws:ec2:*:AccountID:network-interface/*",
                "arn:aws:ec2:*:AccountID:instance/*"
            ],
            "Sid": ""
        },
        {
            "Action": "ssm:GetParameter",
            "Effect": "Allow",
            "Resource": "*",
            "Sid": ""
        },
        {
            "Action": "iam:PassRole",
            "Effect": "Allow",
            "Resource": "arn:aws:iam::AccountID:role/karpenter-eks-uswest-eks-node-group-12345678909876543200000004",
            "Sid": ""
        }
    ],
    "Version": "2012-10-17"
}
```
The above policy works for Karpenter using default launch template. But it does not work for Karpenter using custom launch template.
At AWS console, I created another policy, arn:aws:iam::AccountID:policy/AmazonEKS_Karpenter_Controller_Policy-karpenter-eks-uswest.
This policy works for Karpenter using custom launch template and default launch template. I studied the irsa module. I have no clue how to use this module to create policy as follows and attach it to KarpenterNodeRole-karpenter-eks-uswest. Is it possible to use this module create policy as follows?
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "ec2:CreateLaunchTemplate",
                "ec2:CreateFleet",
                "ec2:RunInstances",
                "ec2:CreateTags",
                "ec2:TerminateInstances",
                "ec2:DeleteLaunchTemplate",
                "ec2:DescribeLaunchTemplates",
                "ec2:DescribeInstances",
                "ec2:DescribeSecurityGroups",
                "ec2:DescribeSubnets",
                "ec2:DescribeImages",
                "ec2:DescribeInstanceTypes",
                "ec2:DescribeInstanceTypeOfferings",
                "ec2:DescribeAvailabilityZones",
                "ec2:DescribeSpotPriceHistory",
                "ssm:GetParameter",
                "pricing:GetProducts"
            ],
            "Resource": "*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "iam:PassRole"
            ],
            "Resource": "arn:aws:iam::AccountID:role/karpenter-eks-uswest-eks-node-group-12345678909876543200000004",
            "Effect": "Allow"
        }
    ]
}
```
## ⚠️ Note

Before you submit an issue, please perform the following first:

1. Remove the local `.terraform` directory (! ONLY if state is stored remotely, which hopefully you are following that best practice!): `rm -rf .terraform/`
2. Re-initialize the project root to pull down modules: `terraform init`
3. Re-attempt your terraform plan or apply and check if the issue still persists

## Versions

- Module version [Required]:
5.4.0
- Terraform version:
v1.3.0
- Provider version(s):
4.33.0

## Reproduction Code [Required]

```
resource "aws_iam_instance_profile" "karpenter" {
  name = "KarpenterNodeInstanceProfile-${var.cluster_name}"
  role = module.eks.eks_managed_node_groups["${var.cluster_name}"].iam_role_name
}

module "karpenter_irsa" {
  source  = "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks"
  version = "5.4.0"

  role_name                               = "KarpenterNodeRole-${var.cluster_name}"

  attach_karpenter_controller_policy      = true

  karpenter_tag_key                       = "karpenter.sh/discovery/${var.cluster_name}"
  karpenter_controller_cluster_id         = module.eks.cluster_id

  karpenter_controller_ssm_parameter_arns = [
    "arn:${local.partition}:ssm:*:*:parameter/aws/service/*"
  ]

  karpenter_controller_node_iam_role_arns = [
    module.eks.eks_managed_node_groups["${var.cluster_name}"].iam_role_arn
  ]

  oidc_providers = {
    ex = {
      provider_arn               = module.eks.oidc_provider_arn
      namespace_service_accounts = ["karpenter:karpenter"]
    }
  }
}
```

## Expected behavior

I would like to use the module create policy as follows:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "ec2:CreateLaunchTemplate",
                "ec2:CreateFleet",
                "ec2:RunInstances",
                "ec2:CreateTags",
                "ec2:TerminateInstances",
                "ec2:DeleteLaunchTemplate",
                "ec2:DescribeLaunchTemplates",
                "ec2:DescribeInstances",
                "ec2:DescribeSecurityGroups",
                "ec2:DescribeSubnets",
                "ec2:DescribeImages",
                "ec2:DescribeInstanceTypes",
                "ec2:DescribeInstanceTypeOfferings",
                "ec2:DescribeAvailabilityZones",
                "ec2:DescribeSpotPriceHistory",
                "ssm:GetParameter",
                "pricing:GetProducts"
            ],
            "Resource": "*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "iam:PassRole"
            ],
            "Resource": "arn:aws:iam::AccountID:role/karpenter-eks-uswest-eks-node-group-12345678909876543200000004",
            "Effect": "Allow"
        }
    ]
}
```
## Actual behavior

The policy created by above code.
```
{
    "Statement": [
        {
            "Action": [
                "pricing:GetProducts",
                "ec2:DescribeSubnets",
                "ec2:DescribeSpotPriceHistory",
                "ec2:DescribeSecurityGroups",
                "ec2:DescribeLaunchTemplates",
                "ec2:DescribeInstances",
                "ec2:DescribeInstanceTypes",
                "ec2:DescribeInstanceTypeOfferings",
                "ec2:DescribeImages",
                "ec2:DescribeAvailabilityZones",
                "ec2:CreateTags",
                "ec2:CreateLaunchTemplate",
                "ec2:CreateFleet"
            ],
            "Effect": "Allow",
            "Resource": "*",
            "Sid": ""
        },
        {
            "Action": [
                "ec2:TerminateInstances",
                "ec2:DeleteLaunchTemplate"
            ],
            "Condition": {
                "StringEquals": {
                    "ec2:ResourceTag/karpenter.sh/discovery/karpenter-eks-uswest": "karpenter-eks-uswest"
                }
            },
            "Effect": "Allow",
            "Resource": "*",
            "Sid": ""
        },
        {
            "Action": "ec2:RunInstances",
            "Condition": {
                "StringEquals": {
                    "ec2:ResourceTag/karpenter.sh/discovery/karpenter-eks-uswest": "karpenter-eks-uswest"
                }
            },
            "Effect": "Allow",
            "Resource": [
                "arn:aws:ec2:*:AccountID:security-group/*",
                "arn:aws:ec2:*:AccountID:launch-template/*"
            ],
            "Sid": ""
        },
        {
            "Action": "ec2:RunInstances",
            "Effect": "Allow",
            "Resource": [
                "arn:aws:ec2:*::image/*",
                "arn:aws:ec2:*:AccountID:volume/*",
                "arn:aws:ec2:*:AccountID:subnet/*",
                "arn:aws:ec2:*:AccountID:spot-instances-request/*",
                "arn:aws:ec2:*:AccountID:network-interface/*",
                "arn:aws:ec2:*:AccountID:instance/*"
            ],
            "Sid": ""
        },
        {
            "Action": "ssm:GetParameter",
            "Effect": "Allow",
            "Resource": "*",
            "Sid": ""
        },
        {
            "Action": "iam:PassRole",
            "Effect": "Allow",
            "Resource": "arn:aws:iam::AccountID:role/karpenter-eks-uswest-eks-node-group-12345678909876543200000004",
            "Sid": ""
        }
    ],
    "Version": "2012-10-17"
}
```

**Comment by bryantbiggs** [comment] 2022-10-05 19:00
you custom launch template needs the auto-discovery tag - you can see an example here https://github.com/clowdhaus/eks-reference-architecture/blob/faa7ab2bab02f67f8fbc4eec74d770d47c556c8a/karpenter/us-east-1/eks.tf#L62

**Comment by apamildner** [comment] 2022-10-26 16:21
@garyyang6 Are you completely sure the launch template you create is tagged with the discovery tag? Go into the AWS console and check the tags. If not, this will not work. Also, you can do  `kubectl logs -l app.kubernetes.io/name=karpenter -nkarpenter -f` and print the error message to help debugging efforts :)

**Comment by bryantbiggs** [comment] 2022-11-23 20:52
closing for now since unable to reproduce. I would also recommend you move to Karpenters node template since it has better support for more functionality than what is available in launch templates

**Closed by bryantbiggs** 2022-11-23 20:52 UTC
Labels: question
